# Generated by Django 5.0.1 on 2024-01-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('field1', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
