# Generated by Django 5.0.1 on 2024-01-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='date_field',
            field=models.DateField(default='2024-01-20'),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='date_time_field',
            field=models.DateTimeField(default='2024-01-20T12:00:00'),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='duration_field',
            field=models.DurationField(default='1 day'),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='email_field',
            field=models.EmailField(default='your_default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='name',
            field=models.CharField(default='Rahim', max_length=255),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='slug_field',
            field=models.SlugField(default='default-slug'),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='text_field',
            field=models.TextField(default='Default text content.'),
        ),
    ]
