# Generated by Django 5.0.1 on 2024-01-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_remove_examplemodel_duration_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='date_field',
        ),
        migrations.RemoveField(
            model_name='examplemodel',
            name='date_time_field',
        ),
    ]
