# Generated by Django 5.0.1 on 2024-01-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_remove_examplemodel_date_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='email_field',
        ),
        migrations.RemoveField(
            model_name='examplemodel',
            name='field1',
        ),
        migrations.RemoveField(
            model_name='examplemodel',
            name='slug_field',
        ),
        migrations.RemoveField(
            model_name='examplemodel',
            name='text_field',
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='address',
            field=models.TextField(default='this is text'),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='father_name',
            field=models.TextField(default='Naim'),
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='roll',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='name',
            field=models.CharField(default='Your Name', max_length=20),
        ),
    ]
